runtime: go111
# service: user-service
env_variables:
  PROJECT_ID: YOUR_PROJECT_ID # Fixme
  # FIRESTORE_EMULATOR_HOST: localhost:8812
  VERSION: v1
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.5
  max_instances: 3
  min_instances: 0